### ISSUE TITLE
Python3 wooey install

### ISSUE THREAD

**Issue by benjaminh** [wooey/Wooey#127]
I tried to install wooey with python 3.4. I used `pip3.4 install wooey` which executed well. But when I had to call `wooey -p ProjectName`, I had an error:

> `Traceback (most recent call last):
File "ProjectName/manage.py", line 8, in <module>
from django.core.management import execute_from_command_line
ImportError: No module named django.core.management`

Django was successfully installed, but I noticed that the shebang in manage.py is pointing to python and not python3. Django was installed is the dist-packages of python3.4…

Is it the expected behaviour (only using wooey with python2.7) ? Did I miss something in the settings for the install ?

Btw, I just changed the shebang in manage.py and made a call to `python3 manage.py runserver` (that told me "You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them." which I did not really understand but I did as it said and it worked well). Then, everything was working and I did not have any other error since that.

Just to let you know about this issue.

**Comment by Chris7** [comment]
Hi @benjaminh,

We use python in the shebang because that will point at the python you consider to be your 'default'. If you want that to be python3.4, you should symlink python to that version. I imagine your default python (when you just type 'python') is python2, and by using pip3.4 you installed wooey under just python3.4. Therefore, 'python' executed python2, which obviously did not have wooey installed.

**Comment by benjaminh** [comment]
Hi @Chris7 ,

I thought my default python command pointed to python3 but I should have realised that it was not the case and pointed to 2.7. Working with different versions is a bit tedious…

Thank you for your answer and sorry for this inconvenience !
