### ISSUE TITLE
Watch folders and automatically update scripts

### ISSUE THREAD

**Issue by mfitzp** [wooey/Wooey#132]
Using [watchdog](https://pypi.python.org/pypi/watchdog) we could support watching folders for updates to scripts and auto-update changed scripts by re-importing.

This might create a lot of spurious script versions in the system depending on how it is used. One workaround would be to auto-remove unused script versions (either on upgrade, or as a maintenance task) which might be a nice-to-have independent on this.

**Comment by Chris7** [comment]
I agree, if a script was never ever run, might as well purge it on version updates.

**Comment by streetmapp** [comment]
Just commenting as this would be something really useful. Unless I'm mistaken, updating a script from the command line currently would cause for a new "script" to be created from a UI perspective. Some mechanism to allow for updating of scripts while maintaining their name, properties, history, etc. would be a great addition.

**Comment by Chris7** [comment]
Just to clarify, we have this through the admin page via 'script versions'. I need to investigate again the command line script addition to see what sort of intelligent choices can be made.

**Comment by streetmapp** [comment]
Understood. Just thinking of being able to automate whatever possible. So
thought being would be able to commit new version of script, which would in
turn deploy the script to the Wooey server, and if Wooey was able to
automatically pick that new version up that would be great.

On July 2, 2016 at 11:13:39 AM, Chris Mitchell (notifications@github.com)
wrote:

Just to clarify, we have this through the admin page via 'script versions'.
I need to investigate again the command line script addition to see what
sort of intelligent choices can be made.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/wooey/Wooey/issues/132#issuecomment-230106517>, or mute
the thread
<https://github.com/notifications/unsubscribe/ACCuhp9zC19FPd74Xjbddrr9Ab6bZhylks5qRoAjgaJpZM4HwL6d>
.

**Comment by Chris7** [comment]
I started work on this here #141. This helps only with the admin interface though.

The issue I'm currently mulling over is how to determine if a script is equivalent or related to an existing script that is in Wooey via the command line.

**Comment by Chris7** [comment]
My current thought is to provide an --update flag that will match script names and go through the update route if found, otherwise add it as a new script.

**Comment by Chris7** [comment]
This is enabled and tested in #141. I'll be merging it in shortly, but would love more testing. Simply add the --update flag and it will attempt to update scripts added via addscripts. For instance:
```
python manage.py --update xxxx.py
```

**Comment by Chris7** [comment]
Supported via #141
