### ISSUE TITLE
Script Markup

### ISSUE THREAD

**Issue by mfitzp** [wooey/Wooey#20]
An interface to edit scripts and provide more detailed, customized documentation.

https://github.com/wooey/django-djangui/issues/5

**Comment by mfitzp** [comment]
By "customized documentation" do you mean instructions, references etc? This would be really nice to have (I'll leave space for it in the UI). In the flask-wooey I read this in from a markdown file but with everything in the database it makes more sense to have a field there to support it, e.g. about or long_description or help?

Do you think it's worth supporting auto-loading markdown files (matching .md file to .py file, or README.md in the same folder) when importing?

**Comment by Chris7** [comment]
I meant instructions/references. I don't think .md file auto-loading is really a good solution -- mainly because with file uploads in the browser you can't auto-detect them (we'd need a separate filefield in the admin for just the markdown). That being said, this is largely just my opinion because I've never encountered cases such as this in the wild.

I'm all for a md/whatever styling though for a more enriched help/long description. I need to run to a lab meeting, so I'll be back in a few hours(yes...3 hour lab meetings are a wonderful thing), but I think we could find app that handles a ton of markup formats for users.

**Comment by mfitzp** [comment]
For the auto-loading I meant on the command line. In the admin I think a straight-up textarea is the best way to go. Markdown is probably the most straightforward to implement - we don't really need to support people writing documents, just a small bit of about text, references, etc. for a script.

We could implement that with Python markdown (`django.contrib.markup`) or just push the rendering onto the front-end with JS. There a few small libraries for this which you can just bind to a div and have it auto-render (good for when we make the UI more dynamic we can skip the render step on the server and just go through JSON).

**Comment by mfitzp** [comment]
Documentation for scripts in #54
