### ISSUE TITLE
Any script get stucked waiting on Windows 10

### ISSUE THREAD

**Issue by csimbi88** [wooey/Wooey#320]
Hi!

I'm absolutely new to Wooey and django. I have successfully installed Wooey, and managed to register scripts as well, but none of them (including the example script is running). I think, the issue is pretty much similar to #218, but still not the same I guess.

I'm using Python 3.7.4 and Django 3.0.5.

Whenever tring to execute a script, I see the prompt running forever, and coming up with the same messages in every second.

Thanks a lot for your help and let me know if any further information is needed.

**Comment by Chris7** [comment]
Are you running a celery instance to execute the jobs?

**Comment by csimbi88** [comment]
I'm using the defaul Wooey setup, so I guess celery is being run there. Is there anything, that needs manual installation maybe?

**Comment by Chris7** [comment]
Celery has to be run separately, you can read more about this here: https://wooey.readthedocs.io/en/latest/running_wooey.html

One thing to note is that a recent user mentioned they had to use gevent on windows instead of eventlet, so this command would change:

`celery -A your_project_name worker --pool=eventlet -l info` to `celery -A your_project_name worker --pool=gevent -l info`

**Comment by Chris7** [comment]
You can also set `WOOEY_CELERY=False` to run the scripts on the main server, which will cause the server to become unresponsive while the jobs are executing however

**Comment by csimbi88** [comment]
Thanks so much. Finally the WOOEY_CELERY=False works fine, the other option ufnortunately doesn't, but for my current purpose it is perfectly fine.
